import { Zap } from "lucide-react";

export const projectsData = {
  currentProjects: [
    {
      id: "current-1",
      title: "Audit Pro",
      description: "Used to help companies for auditing",
      status: "In Improvement",
      progress: 85,
      techStack: ["React", "Node.js", "ESLint", "Express", "MongoDB", "Nextjs"],
      expectedCompletion: "August 2025",
      priority: "high",
      icon: <Zap className="w-6 h-6" />,
    },
    // {
    //   id: 'current-2',
    //   title: 'Real-time Chat Application',
    //   description: 'Developing a scalable chat app with WebSocket integration and modern UI/UX',
    //   status: 'Planning',
    //   progress: 25,
    //   techStack: ['React', 'Socket.io', 'Express', 'PostgreSQL', 'Redis'],
    //   expectedCompletion: 'September 2025',
    //   priority: 'medium',
    //   icon: <Target className="w-6 h-6" />
    // }
  ],
  completedProjects: [
    {
      id: "proj-1",
      title: "Url Shortner",
      description:
        "A lightning-fast URL shortening service with custom aliases, comprehensive analytics, and QR code generation. Features real-time click tracking and user dashboard.",
      image: "/api/placeholder/400/300",
      category: "web-app",
      techStack: ["React", "Node.js", "MongoDB", "Express", "Chart.js"],
      githubLink: "https://github.com/aditya74841/Url_Shortner",
      liveDemoLink: "https://p1.iamadityaranjan.com/",
      features: [
        "Custom URL aliases",
        "Analytics dashboard",
        "QR code generation",
        "Link expiration",
        "Bulk operations",
      ],
      completedDate: "March 2025",
      gradient: "from-blue-500 via-purple-500 to-pink-500",
    },
    {
      id: "proj-2",
      title: "Cura - Lifestyle E-commerce Platform",
      description:
        "A premium e-commerce platform with stunning UI/UX, advanced filtering, wishlist functionality, and seamless checkout experience.",
      image: "/api/placeholder/400/300",
      category: "e-commerce",
      techStack: ["React", "Tailwind CSS", "Redux", "Stripe API", "Firebase"],
      githubLink: "https://github.com/aditya74841/Ecommerce_Frontend.github.io",
      liveDemoLink: "https://p2.iamadityaranjan.com/",
      features: [
        "Product catalog",
        "Shopping cart",
        "Payment integration",
        "Wishlist",
        "Order tracking",
      ],
      completedDate: "February 2025",
      gradient: "from-green-500 via-teal-500 to-blue-500",
    },
    {
      id: "proj-3",
      title: "Google Keep Clone Pro",
      description:
        "An enhanced note-taking app with advanced features like collaborative editing, rich text formatting, and smart categorization.",
      image: "/api/placeholder/400/300",
      category: "productivity",
      techStack: ["React", "Firebase", "Material-UI", "Rich Text Editor"],
      githubLink: "https://github.com/aditya74841/React_TODO_frontend",
      liveDemoLink: "https://p3.iamadityaranjan.com/",
      features: [
        "Rich text editing",
        "Collaborative notes",
        "Smart search",
        "Color coding",
        "Export options",
      ],
      completedDate: "January 2025",
      gradient: "from-yellow-500 via-orange-500 to-red-500",
    },
    {
      id: "proj-4",
      title: "Harmonic Music Portfolio",
      description:
        "An immersive music portfolio with 3D visualizations, interactive audio player, and dynamic waveform displays.",
      image: "/api/placeholder/400/300",
      category: "portfolio",
      techStack: ["React", "Three.js", "Web Audio API", "GSAP", "Tailwind"],
      githubLink: "https://github.com/aditya74841/music_portfolio",
      liveDemoLink: "https://p4.iamadityaranjan.com/",
      features: [
        "3D visualizations",
        "Interactive audio player",
        "Waveform display",
        "Track analytics",
      ],
      completedDate: "December 2024",
      gradient: "from-purple-500 via-pink-500 to-rose-500",
    },
    {
      id: "proj-5",
      title: "TaskMaster Pro",
      description:
        "A comprehensive task management solution with team collaboration, time tracking, and advanced analytics.",
      image: "/api/placeholder/400/300",
      category: "productivity",
      techStack: ["React", "Node.js", "JWT", "MongoDB", "Socket.io"],
      githubLink: "https://github.com",
      liveDemoLink: "https://p5.iamadityaranjan.com/login",
      features: [
        "Team collaboration",
        "Time tracking",
        "Analytics",
        "Project templates",
        "Mobile app",
      ],
      completedDate: "November 2024",
      gradient: "from-indigo-500 via-blue-500 to-cyan-500",
    },
    {
      id: "proj-6",
      title: "NewsFlow - Inshorts Clone",
      description:
        "A modern news aggregation platform with AI-powered summarization, personalized feeds, and offline reading.",
      image: "/api/placeholder/400/300",
      category: "news",
      techStack: ["React", "News API", "PWA", "IndexedDB", "AI Integration"],
      githubLink: "https://github.com/aditya74841/",
      features: [
        "AI summarization",
        "Personalized feeds",
        "Offline reading",
        "Social sharing",
        "Dark mode",
      ],
      completedDate: "October 2024",
      gradient: "from-slate-500 via-gray-600 to-zinc-600",
    },
    {
      id: "proj-7",
      title: "WhatsApp Clone Plus",
      description:
        "A feature-rich messaging app with end-to-end encryption, voice/video calls, and advanced group management.",
      image: "/api/placeholder/400/300",
      category: "messaging",
      techStack: ["React", "Socket.io", "WebRTC", "Node.js", "MongoDB"],
      githubLink: "https://github.com/aditya74841/whatsapp-Clone",
      features: [
        "End-to-end encryption",
        "Voice/video calls",
        "Group management",
        "File sharing",
        "Status updates",
      ],
      completedDate: "September 2024",
      gradient: "from-emerald-500 via-green-500 to-teal-500",
    },
    {
      id: "proj-8",
      title: "QuoteVerse API",
      description:
        "A comprehensive quotes API with advanced filtering, user-generated content, and machine learning recommendations.",
      image: "/api/placeholder/400/300",
      category: "api",
      techStack: ["Node.js", "Express", "MongoDB", "Swagger", "ML Integration"],
      githubLink: "https://github.com/aditya74841/Quote-Backend",
      liveDemoLink: "https://quote-backend-xqfm.onrender.com/api-docs/",
      apiDocsLink: "https://quote-backend-xqfm.onrender.com/api-docs/",
      features: [
        "ML recommendations",
        "User-generated content",
        "Advanced filtering",
        "Rate limiting",
        "Caching",
      ],
      completedDate: "August 2024",
      gradient: "from-violet-500 via-purple-500 to-fuchsia-500",
    },
  ],
  categories: [
    { id: "all", name: "All Projects", count: 8, icon: "🚀" },
    { id: "web-app", name: "Web Apps", count: 2, icon: "💻" },
    { id: "e-commerce", name: "E-commerce", count: 1, icon: "🛒" },
    { id: "productivity", name: "Productivity", count: 2, icon: "📊" },
    { id: "api", name: "APIs", count: 1, icon: "🔗" },
  ],

  // const categories = [
  //     { id: 'all', name: 'All Projects', count: completedProjects.length, icon: '🚀' },
  //     { id: 'web-app', name: 'Web Apps', count: completedProjects.filter(p => p.category === 'web-app').length, icon: '💻' },
  //     { id: 'e-commerce', name: 'E-commerce', count: completedProjects.filter(p => p.category === 'e-commerce').length, icon: '🛒' },
  //     { id: 'productivity', name: 'Productivity', count: completedProjects.filter(p => p.category === 'productivity').length, icon: '📊' },
  //     { id: 'api', name: 'APIs', count: completedProjects.filter(p => p.category === 'api').length, icon: '🔗' }
  //   ];
};
